# Generated by Django 3.2.6 on 2021-08-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_treck_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_number',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
