# Generated by Django 3.2.6 on 2021-08-21 14:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_review_review_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogmodel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('blogTitle', models.CharField(max_length=100)),
                ('blogcontent', models.TextField()),
                ('blogimage', models.ImageField(upload_to='blogimage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
